---
- name: Build Java Application with Maven
  hosts: localhost
  tasks:
    - name: Ensure Maven is installed
      become: yes
      apt:
        name: maven
        state: present

    - name: Build Java application with Maven
      become: yes
      command: mvn clean install
      args:
        chdir: /path/to/helloworld_project
